name: Build pipeline

on:
  push:
    branches:
      - main
      - test_features

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: "npm"

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

  lint:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run lint
        run: yarn run lint

  test:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run tests
        run: yarn run test

  build:
    runs-on: ubuntu-latest
    needs: [setup, lint, test]
    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Install eas-cli globally
        run: yarn global add eas-cli

      - name: Setup Expo
        uses: expo/expo-github-action@v8
        with:
          expo-version: latest
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Pull EAS environment variables
        run: eas env:pull preview

      - name: Build Android app
        run: eas build --platform android --profile preview --local --output ${{ github.workspace }}/app-release.apk

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: ${{ github.workspace }}/app-release.apk
